<a href="https://colab.research.google.com/github/Ian-Leidner/nyu-python-public-policy/blob/master/HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
df = pd.read_csv('/content/drive/My Drive/Data for Python/cleaned_311_data_hw3.csv', header='infer')

In [0]:
df.head()

   Unnamed: 0  Unnamed: 0.1  ...  longitude                                 location
0         238           238  ...        NaN                                      NaN
1         353           353  ... -73.769744  (40.68377771085733, -73.76974413109498)
2         403           403  ...        NaN                                      NaN
3         655           655  ...        NaN                                      NaN
4         658           658  ...        NaN                                      NaN

[5 rows x 43 columns]

In [0]:
#Step 1. Create a function that checks each row in the 311 dataframe to see if the word "graffiti" is present in either the complaint_type value or descriptor value. Both columns may contain the word, so you should check both. If the word "graffiti" is found, the function should return the boolean value True. If "graffiti" is not found, the function should return the boolean value False.

In [0]:
def define_graffiti(row):
  
  if 'Graffiti' in row.complaint_type and pd.notnull(row.descriptor):
      return True
  else:
    return False

df['Graffiti'] = df.apply(define_graffiti, axis=1)

In [7]:
type(define_graffiti)

function

In [22]:
df

       Unnamed: 0  ...  Graffiti
0             238  ...     False
1             353  ...     False
2             403  ...     False
3             655  ...     False
4             658  ...     False
...           ...  ...       ...
64572     2857911  ...     False
64573     2857942  ...     False
64574     2857951  ...     False
64575     2858219  ...     False
64576     2858538  ...     False

[64577 rows x 44 columns]

In [0]:
graffiti_yesno = df.groupby('Graffiti').size()

In [0]:
#Step 2. Apply the function created in Step 1 to the 311 dataframe and create a new column called graffiti_flag that captures the output from the function.

In [28]:
graffiti_yesno

Graffiti
False    39591
True     24986
dtype: int64

In [0]:
#Step 3. Create another dataframe df_graffiti that only contains records where graffiti_flag is True. df_graffiti = df[df.grafitti_flag]

In [0]:
df_Graffiti = df[df.Graffiti]

In [31]:
df_Graffiti

       Unnamed: 0  ...  Graffiti
8             860  ...      True
9             876  ...      True
10            964  ...      True
12           1007  ...      True
13           1013  ...      True
...           ...  ...       ...
64477     2852896  ...      True
64510     2854717  ...      True
64511     2854787  ...      True
64528     2855845  ...      True
64566     2857045  ...      True

[24986 rows x 44 columns]

In [0]:
#Step 4. Group your dataframe df_graffiti to get the count of requests per community_board. Use .nlargest() to identify which Community District has the highest count.

In [33]:
df_Graffiti.groupby('community_board').size().nlargest(20).reset_index(name='Count')

         community_board  Count
0            01 BROOKLYN   1771
1           03 MANHATTAN   1544
2            04 BROOKLYN   1426
3            03 BROOKLYN   1241
4            05 BROOKLYN    958
5            07 BROOKLYN    747
6      Unspecified BRONX    615
7   Unspecified BROOKLYN    579
8           02 MANHATTAN    563
9              01 QUEENS    551
10             12 QUEENS    529
11           14 BROOKLYN    526
12           12 BROOKLYN    520
13           08 BROOKLYN    496
14           17 BROOKLYN    477
15           11 BROOKLYN    469
16             09 QUEENS    465
17              09 BRONX    460
18              06 BRONX    440
19              12 BRONX    416